- hosts: all
  sudo: True
  vars:
    db_sentry:
      name: sentry
      user: sentry
      password: sentry
    superuser_sentry:
      username: admin
      email: admin@example.com
      password: admin
    sentry:
      server: redacted
      url: redacted
      secret_key: 'redacted'
    sentry_mail:
      host: localhost
      port: 25
      username: ''
      password: ''
      use_tls: false
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - sentry

