- hosts: all
  sudo: True
  vars:
    db_sentry:
      name: sentry
      user: sentry
      password: redacted
    superuser_sentry:
      username: admin
      email: redacted
      password: redacted
    sentry:
      server: redacted
      url: redacted
      secret_key: 'redacted'
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - sentry

