---

- name: restart nginx
  debug: msg="will check config before restart"
  changed_when: True
  notify:
    - check nginx configuration
    - restart nginx after check

- name: reload nginx
  debug: msg="will check config before reload"
  changed_when: True
  notify:
    - check nginx configuration
    - reload nginx after check

- name: check nginx configuration
  command: "nginx -t"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no

- name: restart nginx after check
  service: name=nginx state=restarted

- name: reload nginx after check
  service: name=nginx state=reloaded
